### ISSUE TITLE
giscus/utterances for comments

### ISSUE THREAD

**Issue by roaldarbol** [raspberrypi-guide/raspberrypi-guide.github.io#6]
Brief comment on the commenting on the website (which is currently double, both what seems locally and Disqus). I'd just recommend looking into utterances or giscus (which is based on utterances). They use the Github repo for comments, utterances uses issues and giscus uses the discussion section, so depending what you want it could make sense to do that as everything would be logged directly into the GH repo. Another couple of plusses, it's MUCH more lightweight and fast than Disqus, and people'd data is not sold for profit (in the case of Disqus).

**Comment by JolleJolles** [comment]
Thanks for the comment. With much effort I integrated the custom commenting system but because the website is made with github and not wordpress or similar it is hard to inform commenters when they get a reply or even enable them to add an email address that cannot be seen by others so I can email them. As I was getting more and more comments I thought it could be a good idea to provide both the existing system AND Disqus, although I agree with you regarding Disqus. I also thought indeed of a commenting system that uses github issues but then the problem is that you need to have a github account to leave a comment, many visitors to the website may not have.. 

I looked at giscus, which I didn't know about so thanks!, and it looks really good indeed. So maybe the best option would be to remove disqus, include giscus, but keep also the original commenting system but with an added button to include an email address and in that case also send the form as an email with the sender, in which case I can easily reply and thereby notify the commenter. What do you think?

**Comment by roaldarbol** [comment]
Ah, that makes sense - and well done fair integrating it! I think that sounds like a good solid solution, I'd go with it if I was you. I use giscus on my on website, and it was super easy to integrate. I have the script from giscus.app in `giscus.html` in `_includes`, and then `{% include giscus.html %}` in the post template. You can have a look here: https://github.com/roaldarbol/roaldarbol.github.io.

**Comment by JolleJolles** [comment]
I worked today on updating my existing comment system so people do not need any github account either but I can still easily reply to their comment and they get a notification when they enter their email address. That is the most simple and easiest way for my visitors I think. Thanks again for your feedback!
