### ISSUE TITLE
Default pip

### ISSUE THREAD

**Issue by roaldarbol** [raspberrypi-guide/raspberrypi-guide.github.io#7]
In Installing OpenCV, there's a lot of use of `pip`. However, the default python3 pip is `pip3`, so that might cause confusion and the cause for the *Could not find a version that satisfies the requirement opencv-contrib-python (from versions: ) No matching distribution found for opencv-contrib-python* error - at least I got it with pip but not pip3. 
Hope you're well and that Barcelona is treating you well. :-)

**Comment by JolleJolles** [comment]
The pip issue you highlight indeed happens when you also have python2.7 installed and pip is not properly associated with python3. I tend to use (and recommend) working with virtual environments with python3, which results in pip working with python3. But I realise many people may not know about this and still have python2.7 so it is a good point! I updated the guide to reflect your comment (677179b00f5bc73beedc73a26bade49f7530b185). Thanks again for your efforts!

**Comment by roaldarbol** [comment]
Ah, of course! I tend to forget on the Pi... that's on me. But nice with the extra clarifying comment. (Y)
